### PR TITLE
app logos

### PR DESCRIPTION
**Pull request by rajrsingh**
Highly optimized PNGs at different sizes to use in demo apps including a 512x512 for splash screens

### CODE REVIEW

**Comment by bradley-holt** [comment]
@rajrsingh Love it! I think the checkboxes help communicate that it's not a shopping cart app. With the largest one (`app-logos/shoppinglist_splash.png`), perhaps we could make a few changes:

* Remove the URL (since no one is likely to type in the URL anyways)
* Spell out "Progressive Web App" (if we use it)
* Should it say Progressive Web App since not all of them are PWAs?
* Add "Offline First" to the text

The culmination of the above could be something like this…
 
A generic icon that says:  
> Shopping List
> Offline First Demo App from IBM

Optionally we can create multiple icons (one for each type of app) as well…

A PWA icon that says:
> Shopping List
> Offline First Progressive Web App Demo from IBM

A hybrid mobile app icon that says:
> Shopping List
> Offline First Hybrid Mobile App Demo from IBM

A native mobile app icon that says:
> Shopping List
> Offline First Native Mobile App Demo from IBM

A desktop app icon that says:
> Shopping List
> Offline First Desktop App Demo from IBM

**Comment by rajrsingh** [comment]
@bradley-holt I think it's OK to say prog web app on the the splash screen image because it's intended to be used in PWA manifests. If native apps need a similarly sized image we can produce that separately.

**Comment by bradley-holt** [comment]
@rajrsingh In that case, I was thinking that we could create multiple icons (one for each type of app).

**Comment by rajrsingh** [comment]
@bradley-holt new splash screens in the latest commit

**Comment by bradley-holt** [comment]
@rajrsingh Looks great! I'm going to go ahead and merge this.

**Pull request merged**
